name: 여행지 추천 어플리케이션

on:
  push:
    branches:
      - dev
      - feature/*

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - name: Github Repository 불러오기
        uses: actions/checkout@v4
      - name: Node 설치
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: 의존성 설치
        run: npm ci
      - name: env 파일 생성
        run: |
          echo '${{secrets.ENV}}' > .env

  test:
    runs-on: ubuntu-latest
    needs: init
    steps:
      - name: 테스트 코드 실행
        run: npm run test
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: 프로젝트 실행
        run: |
          ^C
          npm run start:dev
